/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/resource/SelectionSimulation copy.vue')['default']
    CourseCodeOptions: typeof import('./src/components/course/CourseCodeOptions.vue')['default']
    CourseResourceItem: typeof import('./src/components/course/CourseResourceItem.vue')['default']
    CourseResourceItemOptions: typeof import('./src/components/course/CourseResourceItemOptions.vue')['default']
    CourseResourceOptions: typeof import('./src/components/CourseResourceOptions.vue')['default']
    CourseResourceSubjectOptions: typeof import('./src/components/course/CourseResourceSubjectOptions.vue')['default']
    CourseSubjectEdit: typeof import('./src/components/course/CourseSubjectEdit.vue')['default']
    CourseSubjectOptions: typeof import('./src/components/course/CourseSubjectOptions.vue')['default']
    CourseTabCoursework: typeof import('./src/components/course/CourseTabCoursework.vue')['default']
    CourseTabInfo: typeof import('./src/components/course/CourseTabInfo.vue')['default']
    CourseTabResult: typeof import('./src/components/course/CourseTabResult.vue')['default']
    CourseTabUser: typeof import('./src/components/course/CourseTabUser.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ProductLogo: typeof import('./src/components/ProductLogo.vue')['default']
    QuestionsOptions: typeof import('./src/components/resource/QuestionsOptions.vue')['default']
    ResourceCategory: typeof import('./src/components/resource/ResourceCategory.vue')['default']
    ResourceCoursewareCategory: typeof import('./src/components/resource/ResourceCoursewareCategory.vue')['default']
    ResourceQuestionsCategory: typeof import('./src/components/resource/ResourceQuestionsCategory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionCourseware: typeof import('./src/components/resource/SelectionCourseware.vue')['default']
    SelectionOrg: typeof import('./src/components/user/SelectionOrg.vue')['default']
    SelectionQuestions: typeof import('./src/components/resource/SelectionQuestions.vue')['default']
    SelectionSimulation: typeof import('./src/components/resource/SelectionSimulation.vue')['default']
    SelectionTestpaper: typeof import('./src/components/resource/SelectionTestpaper.vue')['default']
    SelectionUser: typeof import('./src/components/user/SelectionUser.vue')['default']
    SiteCarousel: typeof import('./src/components/site/SiteCarousel.vue')['default']
    SiteType: typeof import('./src/components/SiteType.vue')['default']
    SystemSettings: typeof import('./src/components/SystemSettings.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    UserOptions: typeof import('./src/components/user/UserOptions.vue')['default']
    UserPanel: typeof import('./src/components/user/UserPanel.vue')['default']
    VNotifications: typeof import('./src/components/VNotifications.vue')['default']
  }
}
