/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ProductLogo: typeof import('./src/components/ProductLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    UserPanel: typeof import('./src/components/UserPanel.vue')['default']
  }
}
