/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/CourseResourceItemOptions copy.vue')['default']
    CourseCodeOptions: typeof import('./src/components/course/CourseCodeOptions.vue')['default']
    CourseResourceItem: typeof import('./src/components/course/CourseResourceItem.vue')['default']
    CourseResourceItemOptions: typeof import('./src/components/course/CourseResourceItemOptions.vue')['default']
    CourseResourceOptions: typeof import('./src/components/CourseResourceOptions.vue')['default']
    CourseResourceSubjectOptions: typeof import('./src/components/course/CourseResourceSubjectOptions.vue')['default']
    CourseSubjectEdit: typeof import('./src/components/course/CourseSubjectEdit.vue')['default']
    CourseSubjectOptions: typeof import('./src/components/course/CourseSubjectOptions.vue')['default']
    FileList: typeof import('./src/components/FileList.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ProductLogo: typeof import('./src/components/ProductLogo.vue')['default']
    QuestionsOptions: typeof import('./src/components/QuestionsOptions.vue')['default']
    ResourceCategory: typeof import('./src/components/resource/ResourceCategory.vue')['default']
    ResourceCoursewareCategory: typeof import('./src/components/resource/ResourceCoursewareCategory.vue')['default']
    ResourceQuestionsCategory: typeof import('./src/components/resource/ResourceQuestionsCategory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionCourseware: typeof import('./src/components/resource/SelectionCourseware.vue')['default']
    SiteType: typeof import('./src/components/SiteType.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    UserPanel: typeof import('./src/components/UserPanel.vue')['default']
    VNotifications: typeof import('./src/components/VNotifications.vue')['default']
  }
}
