/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/apply': RouteRecordInfo<'/apply', '/apply', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/[path]': RouteRecordInfo<'/home/[path]', '/home/:path', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/home/[path]/': RouteRecordInfo<'/home/[path]/', '/home/:path', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/home/[path]/[id]': RouteRecordInfo<'/home/[path]/[id]', '/home/:path/:id', { path: ParamValue<true>, id: ParamValue<true> }, { path: ParamValue<false>, id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/manage': RouteRecordInfo<'/manage', '/manage', Record<never, never>, Record<never, never>>,
    '/manage/': RouteRecordInfo<'/manage/', '/manage', Record<never, never>, Record<never, never>>,
    '/manage/apply/account': RouteRecordInfo<'/manage/apply/account', '/manage/apply/account', Record<never, never>, Record<never, never>>,
    '/manage/apply/review': RouteRecordInfo<'/manage/apply/review', '/manage/apply/review', Record<never, never>, Record<never, never>>,
    '/manage/correct': RouteRecordInfo<'/manage/correct', '/manage/correct', Record<never, never>, Record<never, never>>,
    '/manage/course/': RouteRecordInfo<'/manage/course/', '/manage/course', Record<never, never>, Record<never, never>>,
    '/manage/course/analyse': RouteRecordInfo<'/manage/course/analyse', '/manage/course/analyse', Record<never, never>, Record<never, never>>,
    '/manage/dc/exam': RouteRecordInfo<'/manage/dc/exam', '/manage/dc/exam', Record<never, never>, Record<never, never>>,
    '/manage/dc/student': RouteRecordInfo<'/manage/dc/student', '/manage/dc/student', Record<never, never>, Record<never, never>>,
    '/manage/notice': RouteRecordInfo<'/manage/notice', '/manage/notice', Record<never, never>, Record<never, never>>,
    '/manage/org': RouteRecordInfo<'/manage/org', '/manage/org', Record<never, never>, Record<never, never>>,
    '/manage/resource/courseware': RouteRecordInfo<'/manage/resource/courseware', '/manage/resource/courseware', Record<never, never>, Record<never, never>>,
    '/manage/resource/questions': RouteRecordInfo<'/manage/resource/questions', '/manage/resource/questions', Record<never, never>, Record<never, never>>,
    '/manage/resource/share': RouteRecordInfo<'/manage/resource/share', '/manage/resource/share', Record<never, never>, Record<never, never>>,
    '/manage/resource/simulation': RouteRecordInfo<'/manage/resource/simulation', '/manage/resource/simulation', Record<never, never>, Record<never, never>>,
    '/manage/resource/testpaper': RouteRecordInfo<'/manage/resource/testpaper', '/manage/resource/testpaper', Record<never, never>, Record<never, never>>,
    '/manage/site': RouteRecordInfo<'/manage/site', '/manage/site', Record<never, never>, Record<never, never>>,
    '/manage/system/database': RouteRecordInfo<'/manage/system/database', '/manage/system/database', Record<never, never>, Record<never, never>>,
    '/manage/system/dict': RouteRecordInfo<'/manage/system/dict', '/manage/system/dict', Record<never, never>, Record<never, never>>,
    '/manage/system/log': RouteRecordInfo<'/manage/system/log', '/manage/system/log', Record<never, never>, Record<never, never>>,
    '/manage/system/parameter-setting': RouteRecordInfo<'/manage/system/parameter-setting', '/manage/system/parameter-setting', Record<never, never>, Record<never, never>>,
    '/manage/user/[roleId]': RouteRecordInfo<'/manage/user/[roleId]', '/manage/user/:roleId', { roleId: ParamValue<true> }, { roleId: ParamValue<false> }>,
    '/manage/user/permission': RouteRecordInfo<'/manage/user/permission', '/manage/user/permission', Record<never, never>, Record<never, never>>,
    '/manage/user/role': RouteRecordInfo<'/manage/user/role', '/manage/user/role', Record<never, never>, Record<never, never>>,
  }
}
