/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/about': RouteRecordInfo<'/home/about', '/home/about', Record<never, never>, Record<never, never>>,
    '/home/articles': RouteRecordInfo<'/home/articles', '/home/articles', Record<never, never>, Record<never, never>>,
    '/home/articles/[id]': RouteRecordInfo<'/home/articles/[id]', '/home/articles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/home/articles/edit-demo': RouteRecordInfo<'/home/articles/edit-demo', '/home/articles/edit-demo', Record<never, never>, Record<never, never>>,
    '/home/news/': RouteRecordInfo<'/home/news/', '/home/news', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/manage': RouteRecordInfo<'/manage', '/manage', Record<never, never>, Record<never, never>>,
    '/manage/': RouteRecordInfo<'/manage/', '/manage', Record<never, never>, Record<never, never>>,
  }
}
